name: Build Pixel 8a Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache

          df -h

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y \
            git curl bc bison flex \
            zip unzip rsync \
            python3 python3-pip \
            clang lld llvm

      - name: Clone sources
        run: |
          chmod +x scripts/clone.sh
          ./scripts/clone.sh

      - name: Build
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: kernel-output
          path: out/
